source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-simple-navigation'
gem 'simple-navigation-bootstrap'
gem 'thin'
gem 'padrino'
gem 'activerecord'
gem 'sinatra-flash'
gem 'sinatra-redirect-with-flash'